### PR TITLE
Calendar total basic calendar view  #210, #160

### PR DESCRIPTION
**Pull request by luriusTM**
I still think this will open more topics, than it solves, but the topics can be kicked out this way :)

### CODE REVIEW

**Comment by eythaann** [comment]
@luriusTM please ask for for components or libraries before add it to the project on the discord channel, in the project the used library is Antd, and it has a calendar component.

**Comment by eythaann** [comment]
join us on discord to get a better communication ;)

**Comment by luriusTM** [comment]
> @luriusTM please ask for for components or libraries before add it to the project on the discord channel, in the project the used library is Antd, and it has a calendar component.

This will take them a bit of time... antd calendar is more... felxible, which means more work to achive kind the same with it.

**Comment by luriusTM** [comment]
> join us on discord to get a better communication ;)

will do, just this week is a bit busy and not yet had time to focus on something... like account restore and kind like that... I did not use the discord since some time...

**Pull request closed without merging**
