### PR TITLE
Adding HWND persistance on the monitor scope

### PR DESCRIPTION
**Pull request by luriusTM**
Tested on the past few days, I did not experiance any glitch, yet.

### CODE REVIEW

**Comment by luriusTM** [comment]
Dependency after the merge of new setup created: 
https://github.com/eythaann/Seelen-UI/pull/284/files#diff-a7d04ea868090f29a8411ce85285c6db2b5d14db556378ba84ddbc9d6416e3e8

**Comment by luriusTM** [comment]
After experiencing with the new system setup, there is PR dependency in between: 
https://github.com/eythaann/Seelen-UI/pull/288

The primary monitor change detection will be only possible to detect after both PRs are accepted. This will make the solution complete. Til' then, when you change primary monitor, this will not take affect on Seelen. 

(modification is needed, because after this there will be a notification channel from BE to FR, in this way, there can be updates passed through.)

**Comment by luriusTM** [comment]
Dependency is still there.

**Comment by eythaann** [comment]
waiting for resolution of https://github.com/Seelen-Inc/slu-lib/pull/1 to be merged.

**Comment by eythaann** [comment]
After a commit is added to the library, I need to run some workflow on our side to auto update the dependencies, wait until I add to merge this. Maybe Dependabot is the best option.

**Comment by eythaann** [comment]
Library updated on: https://github.com/eythaann/Seelen-UI/pull/346

**Comment by luriusTM** [comment]
> Library updated on: #346

still not finds the appropriate version... ^^

**Comment by luriusTM** [comment]
> Library updated on: #346 - @luriusTM please make git pull of master to pass the ci.

done

**Pull request merged**
