### PR TITLE
Calendar view style & onWheel function apply #274

### PR DESCRIPTION
**Pull request by luriusTM**
Now it is applied on a wrapper div, so will not affect the popup, but the calendar. 

Rewritten it to override defaults and use in styles only the self made styles. 

These was the review comments for the previous style problems. Only some minor style element is not possible this way, but it is not so recognisable. 

Current:
image

### CODE REVIEW

**Comment by eythaann** [comment]
now the classes are ok, but the style doesn't match with the rest of the app, remove transparency and use a solid color just like it is now without transparency just a plain gray-50.

**Comment by eythaann** [comment]
Also the selected day should have rounder corners, and be solid color.

**Comment by eythaann** [comment]
also the days that aren't part of the month should be shown, not hiding.

**Comment by luriusTM** [comment]
> now the classes are ok, but the style doesn't match with the rest of the app, remove transparency and use a solid color just like it is now without transparency just a plain gray-50.

> Also the selected day should have rounder corners, and be solid color.

> also the days that aren't part of the month should be shown, no hidden

Yes master! :) 
image

**Comment by eythaann** [comment]
make de month clickable to get the month view:
image
image
image

**Comment by luriusTM** [comment]
> Make the header clickable to get the month view just like current implementation allows (if I wanna see the date where I was born for example is hard to fit the date with only the day-to-day view): image image image


I'm not sure you are right or not... this view is mostly for some short upcoming ones... or at least I use it for maybe for next month, or next year, I do not browse half a decade ago, if I want something like that, I use an outlook or a calendar app. But as you wish:

https://github.com/user-attachments/assets/3287656f-6048-4c23-bb34-be881bc8e86d

And this component do not have a decade view... please do not ask that :D

**Comment by eythaann** [comment]
hahaha only with the month-to-month is ok.

**Pull request merged**
